### ISSUE TITLE
Panic in `ftl dev`

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1404]
```
panic: send on closed channel
	panic: channel not subscribed

goroutine 26 [running]:
github.com/alecthomas/types/pubsub.(*Topic[...]).Unsubscribe(0x105491d20, 0x140000e6ba0)
	/Users/alec/go/pkg/mod/github.com/alecthomas/types@v0.14.0/pubsub/pubsub.go:139 +0xb4
panic({0x10523d5c0?, 0x105453c60?})
	/Users/alec/Library/Caches/hermit/pkg/go-1.22.2/src/runtime/panic.go:770 +0x124
github.com/alecthomas/types/pubsub.(*Topic[...]).Close(...)
	/Users/alec/go/pkg/mod/github.com/alecthomas/types@v0.14.0/pubsub/pubsub.go:152
github.com/TBD54566975/ftl/buildengine.(*Engine).watchForModuleChanges(0x140004c1170, {0x10546af10, 0x1400051f7c0}, 0x1dcd6500)
	/Users/alec/dev/ftl/buildengine/engine.go:278 +0xdcc
github.com/TBD54566975/ftl/buildengine.(*Engine).Dev(0x140004c1170, {0x10546af10, 0x1400051f7c0}, 0x1dcd6500, {{0x14000681e60?, 0x1?, 0x1?}})
	/Users/alec/dev/ftl/buildengine/engine.go:236 +0x90
main.(*devCmd).Run.func2()
	/Users/alec/dev/ftl/cmd/ftl/cmd_dev.go:81 +0x48c
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/alec/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
	/Users/alec/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98
```

**Comment by matt2e** [comment]
Yep, this looks fixed
