### ISSUE TITLE
nil pointer dereference panic on bad import with ingress

### ISSUE THREAD

**Issue by gak** [TBD54566975/ftl#1828]
This module has a missing `ftl/builtin` import, but FTL is crashing.

```go
package chicken

import (
	"context"

	"github.com/TBD54566975/ftl/go-runtime/ftl"
)

type FuncRequest struct {
}

type FuncResponse struct {
}

//ftl:ingress GET /url/path
func Func(ctx context.Context, req builtin.HttpRequest[FuncRequest]) (builtin.HttpResponse[FuncResponse, string], error) {
	// TODO: Implement
	return builtin.HttpResponse[FuncResponse, string]{
		Status: 200,
		Body: ftl.Some(FuncResponse{}),
	}, nil
}
```

```
info: Starting FTL with 1 controller(s)
info:controller0: Web console available at: http://localhost:8892
info:controller0: HTTP ingress server listening on: http://localhost:8891
info:chicken: Building module
info:database: Building module
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x30 pc=0x102a91660]

goroutine 4273 [running]:
github.com/TBD54566975/ftl/backend/schema.Visit.func1()
	/Users/gak/src/ftl/backend/schema/visit.go:6 +0x20
github.com/TBD54566975/ftl/go-runtime/schema/finalize.hasFailedRef.func1({0x0?, 0x0?}, 0x14000fb5b01?)
	/Users/gak/src/ftl/go-runtime/schema/finalize/analyzer.go:125 +0x130
github.com/TBD54566975/ftl/backend/schema.Visit({0x0, 0x0}, 0x140003d47a0)
	/Users/gak/src/ftl/backend/schema/visit.go:5 +0x8c
github.com/TBD54566975/ftl/go-runtime/schema/finalize.hasFailedRef({0x0, 0x0}, {0x104370110, 0x140003d4480})
	/Users/gak/src/ftl/go-runtime/schema/finalize/analyzer.go:122 +0x9c
github.com/TBD54566975/ftl/go-runtime/schema/finalize.propagateTypeErrors(0x1400028ed20, 0x140014014a0?, {0x104370110, 0x140003d4480})
	/Users/gak/src/ftl/go-runtime/schema/finalize/analyzer.go:107 +0x140
github.com/TBD54566975/ftl/go-runtime/schema/finalize.combineExtractorResults(0x1400028ed20, {0x1400013d0c4, 0x7})
	/Users/gak/src/ftl/go-runtime/schema/finalize/analyzer.go:90 +0x250
github.com/TBD54566975/ftl/go-runtime/schema/finalize.Run(0x1400028ed20)
	/Users/gak/src/ftl/go-runtime/schema/finalize/analyzer.go:46 +0xb8
github.com/TBD54566975/golang-tools/go/analysis/internal/checker.(*action).execOnce(0x14001098460)
	/Users/gak/go/pkg/mod/github.com/!t!b!d54566975/golang-tools@v0.2.1/go/analysis/internal/checker/checker.go:828 +0x890
sync.(*Once).doSlow(0x14000fb5fa8?, 0x102c8b910?)
	/Users/gak/Library/Caches/hermit/pkg/go-1.22.4/src/sync/once.go:74 +0x100
sync.(*Once).Do(...)
	/Users/gak/Library/Caches/hermit/pkg/go-1.22.4/src/sync/once.go:65
github.com/TBD54566975/golang-tools/go/analysis/internal/checker.(*action).exec(...)
	/Users/gak/go/pkg/mod/github.com/!t!b!d54566975/golang-tools@v0.2.1/go/analysis/internal/checker/checker.go:743
github.com/TBD54566975/golang-tools/go/analysis/internal/checker.execAll.func1(0x0?)
	/Users/gak/go/pkg/mod/github.com/!t!b!d54566975/golang-tools@v0.2.1/go/analysis/internal/checker/checker.go:731 +0x4c
created by github.com/TBD54566975/golang-tools/go/analysis/internal/checker.execAll in goroutine 386
	/Users/gak/go/pkg/mod/github.com/!t!b!d54566975/golang-tools@v0.2.1/go/analysis/internal/checker/checker.go:737 +0x144
[Error - 10:33:56] Server process exited with code 2.
```

**Comment by worstell** [comment]
i think this was fixed with the changes [here](https://github.com/TBD54566975/ftl/pull/1711/files#diff-d29e783a68e9e5132f46532d3c559798bf6db9b691532eebe2433294085cb935) - it's not reproing for me
