### ISSUE TITLE
Rare panic in `analizersWithDependencies`

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2072]
I saw a panic while running `ftl dev`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1001bddd0]

goroutine 3827 [running]:
github.com/TBD54566975/ftl/go-runtime/schema.analyzersWithDependencies(...)
	/Users/mtoohey/Code/ftl/go-runtime/schema/extract.go:114
github.com/TBD54566975/ftl/go-runtime/schema.Extract({0x14000a631d0?, 0xc19d3a7a89401a60?})
	/Users/mtoohey/Code/ftl/go-runtime/schema/extract.go:98 +0x29c
github.com/TBD54566975/ftl/go-runtime/compile.ExtractModuleSchema({0x14000a631d0, 0x27}, 0x140002f6100)
	/Users/mtoohey/Code/ftl/go-runtime/compile/build.go:857 +0x38
github.com/TBD54566975/ftl/go-runtime/compile.Build({0x1017fdd78, 0x1400087e3c0}, {0x14000292750, 0x17}, {0x14000a631d0, 0x27}, 0x140002f6100, {0x129512f78, 0x140006804e0})
	/Users/mtoohey/Code/ftl/go-runtime/compile/build.go:156 +0x860
github.com/TBD54566975/ftl/buildengine.buildGoModule({0x1017fdd78?, 0x1400087e3c0?}, {0x14000292750?, 0x17?}, _, {{{0x14000a631d0, 0x27}, {0x140005a3760, 0x2}, {0x140005a3764, ...}, ...}, ...}, ...)
	/Users/mtoohey/Code/ftl/buildengine/build_go.go:12 +0x70
github.com/TBD54566975/ftl/buildengine.buildModule({0x1017fdd78, 0x1400087e330}, {0x14000292750, 0x17}, _, {{{0x14000a631d0, 0x27}, {0x140005a3760, 0x2}, {0x140005a3764, ...}, ...}, ...}, ...)
	/Users/mtoohey/Code/ftl/buildengine/build.go:49 +0x56c
github.com/TBD54566975/ftl/buildengine.Build(...)
	/Users/mtoohey/Code/ftl/buildengine/build.go:26
github.com/TBD54566975/ftl/buildengine.(*Engine).build(0x14000350380, {0x1017fdd78, 0x1400087e330}, {0x140003d6a85, 0x3}, 0x14000c01140, 0x140013136e0)
	/Users/mtoohey/Code/ftl/buildengine/engine.go:699 +0x34c
github.com/TBD54566975/ftl/buildengine.(*Engine).tryBuild(0x14000350380, {0x1017fdd78, 0x1400087e330}, 0x14000bfa210, {0x140003d6a85, 0x3}, 0x14000c01140, 0x140013136e0, 0x140000edd80)
	/Users/mtoohey/Code/ftl/buildengine/engine.go:667 +0x2b0
github.com/TBD54566975/ftl/buildengine.(*Engine).buildWithCallback.func2()
	/Users/mtoohey/Code/ftl/buildengine/engine.go:602 +0x3a4
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/mtoohey/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x58
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 393
	/Users/mtoohey/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75 +0x98
```

It only happened once and I could not reproduce it.

**Comment by worstell** [comment]
going to close as I haven't been able to repro this and `extract.go` has undergone a lot of change in the last couple of weeks
