### ISSUE TITLE
Failed to get deployments when polling panic

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#2402]
This happened while I had the `ftl dev --recreate` command running locally for a long period of time. It just randomly stopped during a deployment with the following error.

```sh
info: time's schema changed; processing echo
info:echo: Building module
info:echo: Module built (2.30s)
info:echo: Deploying module
info:controller0: Reusing deployment: dpl-echo-meyrqyrnyv4fc1k
info: All modules deployed, watching for changes...
info:time: Building module
info:time: Module built (3.45s)
info:time: Deploying module
info:controller0: Stopped dpl-time-4zypn4w2y2o6cuym
info:controller0: Deployed dpl-time-xvtequb7lz7dt5y
info: time's schema changed; processing echo
info:echo: Building module
info:echo: Module built (2.28s)
info:echo: Deploying module
info:controller0: Reusing deployment: dpl-echo-meyrqyrnyv4fc1k
info: All modules deployed, watching for changes...
error:controller0: Could not deregister runner http://127.0.0.1:8894 (rnr-1-ms3qgzzadv7bley): unexpected EOF
error:controller0: failed to get deployments when polling: failed to connect to `user=postgres database=ftl`:
	[::1]:15432 (localhost): failed to receive message: read tcp [::1]:64345->[::1]:15432: read: connection reset by peer
	127.0.0.1:15432 (localhost): failed to receive message: read tcp 127.0.0.1:64346->127.0.0.1:15432: read: connection reset by peer
error:controller0: failed to get deployments when polling: failed to connect to `user=postgres database=ftl`:
	[::1]:15432 (localhost): failed to receive message: read tcp [::1]:64349->[::1]:15432: read: connection reset by peer
	127.0.0.1:15432 (localhost): failed to receive message: read tcp 127.0.0.1:64350->127.0.0.1:15432: read: connection reset by peer
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10513ddec]

goroutine 553873 [running]:
github.com/TBD54566975/ftl/backend/controller.(*Service).executeAsyncCalls(0x1400072d200, {0x10629a8f8, 0x140008894d0})
	/Users/me/dev/ftl/backend/controller/controller.go:1405 +0x7cc
github.com/TBD54566975/ftl/backend/controller.New.New.func1.func6({0x10629a8f8?, 0x140008894d0?})
	/Users/me/dev/ftl/backend/controller/controller.go:270 +0x34
github.com/TBD54566975/ftl/backend/controller/scheduledtask.(*Scheduler).run.func2()
	/Users/me/dev/ftl/backend/controller/scheduledtask/scheduledtask.go:148 +0x50
created by github.com/TBD54566975/ftl/backend/controller/scheduledtask.(*Scheduler).run in goroutine 189
	/Users/me/dev/ftl/backend/controller/scheduledtask/scheduledtask.go:147 +0xc7c
```

**Comment by matt2e** [comment]
> github.com/TBD54566975/ftl/backend/controller.(*Service).executeAsyncCalls(0x1400072d200, {0x10629a8f8, 0x140008894d0})
> 	/Users/me/dev/ftl/backend/controller/controller.go:1405 +0x7cc

I think the underlying issue was this one: https://github.com/TBD54566975/ftl/issues/2539
