### ISSUE TITLE
Race condition related to encryption: concurrent map writes, getDerivedPrimitive

### ISSUE THREAD

**Issue by gak** [TBD54566975/ftl#2466]
https://github.com/TBD54566975/ftl/actions/runs/10479096401/attempts/1

```
    harness.go:327: debug: fatal error: concurrent map writes
    harness.go:327: debug: 
    harness.go:327: debug: goroutine 2481 [running]:
    harness.go:327: debug: github.com/TBD54566975/ftl/internal/encryption.(*KMSEncryptor).getDerivedPrimitive(0xc0005a31c0, {0x7fd7242d3b78, 0xc00133f608})
```

**Comment by alecthomas** [comment]
You probably know this already after eyeballing it, but that map needs a lock around it.
