### ISSUE TITLE
panic: unhandled type: <nil> in schema.TypeFromProto

### ISSUE THREAD

**Issue by gak** [TBD54566975/ftl#2633]
Looks like a bad local state, since I can go to an much older commit with the same error.

```
just clean && ftl dev examples/go --log-level debug

debug:controller0: Done in 5.5s
info:controller0: Web console available at: http://127.0.0.1:8892
debug:controller0: Listening on http://127.0.0.1:8892
debug:controller0: Advertising as http://127.0.0.1:8892
info:controller0: HTTP ingress server listening on: http://127.0.0.1:8891
debug:controller0: Seeded 0 deployments
panic: unhandled type: <nil>

goroutine 189 [running]:
github.com/TBD54566975/ftl/backend/schema.TypeFromProto(0x0?)
	/Users/gak/src/ftl/backend/schema/protobuf_dec.go:88 +0x784
github.com/TBD54566975/ftl/backend/schema.fieldToSchema(0x140007b9e00)
	/Users/gak/src/ftl/backend/schema/field.go:76 +0x64
github.com/TBD54566975/ftl/backend/schema.fieldListToSchema(...)
	/Users/gak/src/ftl/backend/schema/field.go:66
github.com/TBD54566975/ftl/backend/schema.DataFromProto(0x140007f9600)
	/Users/gak/src/ftl/backend/schema/data.go:203 +0x250
github.com/TBD54566975/ftl/backend/schema.declListToSchema({0x140001d1520, 0x4, 0x14000000101?})
	/Users/gak/src/ftl/backend/schema/protobuf_dec.go:39 +0x150
github.com/TBD54566975/ftl/backend/schema.ModuleFromProto(0x14000a79e80)
	/Users/gak/src/ftl/backend/schema/module.go:239 +0x68
github.com/TBD54566975/ftl/backend/schema.ModuleFromBytes({0x1400005e580, 0x516, 0x516})
	/Users/gak/src/ftl/backend/schema/module.go:249 +0x74
github.com/TBD54566975/ftl/backend/schema.(*Module).Scan(0x1400060c850, {0x101d88400?, 0x14000306240?})
	/Users/gak/src/ftl/backend/schema/module.go:38 +0x5c
database/sql.convertAssignRows({0x1020e1cc0, 0x1400060c850}, {0x101d88400, 0x14000306240}, 0x14000a76b40)
	/Users/gak/Library/Caches/hermit/pkg/go-1.23.0/src/database/sql/convert.go:396 +0x1b5c
database/sql.convertAssignRows({0x101d84ec0, 0x14000a76c30}, {0x101d88400, 0x14000306240}, 0x14000a76b40)
	/Users/gak/Library/Caches/hermit/pkg/go-1.23.0/src/database/sql/convert.go:439 +0x1984
database/sql.(*Rows).Scan(0x14000a76b40, {0x1400079f6d8, 0x9, 0x10178b04d?})
	/Users/gak/Library/Caches/hermit/pkg/go-1.23.0/src/database/sql/sql.go:3392 +0x404
github.com/TBD54566975/ftl/backend/controller/dal/internal/sql.(*Queries).GetDeploymentsWithMinReplicas(0x14000580808?, {0x1021b05f8?, 0x14000a82c30?})
	/Users/gak/src/ftl/backend/controller/dal/internal/sql/queries.sql.go:1057 +0x1e4
github.com/TBD54566975/ftl/backend/controller/dal.(*DAL).GetDeploymentsWithMinReplicas(0x14000a0e7f8?, {0x1021b05f8?, 0x14000a82c30?})
	/Users/gak/src/ftl/backend/controller/dal/dal.go:858 +0x30
github.com/TBD54566975/ftl/backend/controller/dal.(*DAL).PollDeployments(0x140003da680, {0x1021b05f8, 0x14000a82c30})
	/Users/gak/src/ftl/backend/controller/dal/notify.go:71 +0xd0
created by github.com/TBD54566975/ftl/backend/controller.(*Service).watchModuleChanges in goroutine 180
	/Users/gak/src/ftl/backend/controller/controller.go:1886 +0x3d0
...

**Comment by gak** [comment]
Fixed with `--recreate`
