### ISSUE TITLE
Fix a flaky panic from running `ftl dev`

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2660]
Didn't want to interrupt another task I was in the middle of so throwing this into an issue. I was only able to get it to happen the once, so this is quite low priority.

```
$ ftl dev --recreate ../<our customer team>
go: downloading golang.org/x/term v0.24.0
go: downloading github.com/docker/docker v27.2.1+incompatible
info: Starting FTL with 1 controller(s)
info: possible database version mismatch, expecting to use container image postgres:15.8 for container with name ftl-db-1, bit it was already running with image postgres
info:controller0: Web console available at: http://127.0.0.1:8892
info:controller0: HTTP ingress server listening on: http://127.0.0.1:8891
info: Controller started in 15.007827s
info: FTL startup command ⚡️
info:REDACTED: Building module
info:REDACTED: Building module
info:REDACTED: Building module
info:REDACTED: Building module
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102a312bc]

goroutine 581 [running]:
github.com/TBD54566975/ftl/go-runtime/schema.analyzersWithDependencies()
	/Users/dli/Development/ftl/go-runtime/schema/extract.go:294 +0x118
github.com/TBD54566975/ftl/go-runtime/schema.Extract({0x14000d7d8c0?, 0x103b7e5d6?})
	/Users/dli/Development/ftl/go-runtime/schema/extract.go:111 +0xd8
github.com/TBD54566975/ftl/go-runtime/compile.Build({0x104613198, 0x14000127e00}, {0x14000662a20, 0x1a}, {0x14000d7d8c0, 0x30}, 0x1400037e540, {0x14c6b5f00, 0x140001780e0}, {0x0, ...})
	/Users/dli/Development/ftl/go-runtime/compile/build.go:167 +0x90c
github.com/TBD54566975/ftl/internal/buildengine.buildGoModule({0x104613198?, _}, {_, _}, _, {{{0x14000d7d8c0, 0x30}, {0x14000b03ac8, 0x2}, {0x14000b03acc, ...}, ...}, ...}, ...)
	/Users/dli/Development/ftl/internal/buildengine/build_go.go:12 +0x80
github.com/TBD54566975/ftl/internal/buildengine.buildModule({0x104613198, _}, {_, _}, _, {{{0x14000d7d8c0, 0x30}, {0x14000b03ac8, 0x2}, {0x14000b03acc, ...}, ...}, ...}, ...)
	/Users/dli/Development/ftl/internal/buildengine/build.go:49 +0x580
github.com/TBD54566975/ftl/internal/buildengine.Build(...)
	/Users/dli/Development/ftl/internal/buildengine/build.go:26
github.com/TBD54566975/ftl/internal/buildengine.(*Engine).build(0x140008f0460, {0x104613198, 0x14000127d10}, {0x14000b02cf5, 0x5}, 0x14000fe36b0, 0x140006462a0)
	/Users/dli/Development/ftl/internal/buildengine/engine.go:708 +0x354
github.com/TBD54566975/ftl/internal/buildengine.(*Engine).tryBuild(0x140008f0460, {0x104613198, 0x14000127d10}, 0x14000156180, {0x14000b02cf5, 0x5}, 0x14000fe36b0, 0x140006462a0, 0x1400024a6a0)
	/Users/dli/Development/ftl/internal/buildengine/engine.go:676 +0x294
github.com/TBD54566975/ftl/internal/buildengine.(*Engine).buildWithCallback.func2()
	/Users/dli/Development/ftl/internal/buildengine/engine.go:611 +0x3a0
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/dli/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x54
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 304
	/Users/dli/go/pkg/mod/golang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x98
```

**Comment by deniseli** [comment]
Nonredacted stacktrace in https://sq-tbd.slack.com/archives/C06UQDEQUMU/p1726164218391329

**Comment by stuartwdouglas** [comment]
Possibly similar to https://github.com/TBD54566975/ftl/issues/2251

**Comment by deniseli** [comment]
removing the `good first issue` label since this one is apparently cursed
