### ISSUE TITLE
TestKubeScaling flaky failing with "Unary RPC failed: not_found: could not resolve reference echo.echo"

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#2897]
```
harness.go:396: debug: Unary RPC failed: not_found: could not resolve reference echo.echo: not found: /xyz.block.ftl.v1.VerbService/Call
panic: integration.TestingError("Did not expect an error but got:
	not_found: could not resolve reference echo.echo: not found")

goroutine 51 [running]:
github.com/TBD54566975/ftl/internal/integration.T.Fatalf(...)
	/home/runner/work/ftl/ftl/internal/integration/wrapper.go:20
github.com/alecthomas/assert/v2.NoError({0x3403e20, 0xc000434460}, {0x33b6ae0, 0xc000455c80}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/alecthomas/assert/v2@v2.11.0/assert.go:234 +0x1a8
github.com/TBD54566975/ftl/backend/controller/scaling_test.TestKubeScaling.func3.1.Call[...].2({{0x33dc488, 0xc0003931d0}, {0xc000[363](https://github.com/TBD54566975/ftl/actions/runs/11098566294/job/30831458592?pr=2894#step:8:364)500, 0x24}, {0xc000114c80, 0x19}, {0xc00019b440, 0x40}, {0xc0003d2b70, 0x27}, ...})
	/home/runner/work/ftl/ftl/internal/integration/actions.go:381 +0x58f
github.com/TBD54566975/ftl/backend/controller/scaling_test.TestKubeScaling.func3.1()
	/home/runner/work/ftl/ftl/backend/controller/scaling/kube_scaling_integration_test.go:46 +0x2b3
created by github.com/TBD54566975/ftl/backend/controller/scaling_test.TestKubeScaling.func3 in goroutine 35
	/home/runner/work/ftl/ftl/backend/controller/scaling/kube_scaling_integration_test.go:38 +0x229
FAIL	github.com/TBD54566975/ftl/backend/controller/scaling	162.780s
```

eg. [here](https://github.com/TBD54566975/ftl/actions/runs/11098566294/job/30831458592?pr=2894)

**Comment by stuartwdouglas** [comment]
https://github.com/TBD54566975/ftl/pull/2921 may help
