### ISSUE TITLE
Panic creating a module outside of an FTL project

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#3012]
```
mtoohey ~/Code  $ ./ftl/build/release/ftl new go . example
panic: project config path must be absolute: 

goroutine 1 [running]:
github.com/TBD54566975/ftl/internal/projectconfig.Config.Root({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x0, {0x0, 0x0, 0x0}, ...})
	/Users/mtoohey/Code/ftl/internal/projectconfig/projectconfig.go:46 +0x94
main.newCmd.Run({{0x140002fa4f0, 0x2}, {0x10315b8d0, 0x1}, {0x140002fa530, 0x7}}, {0x1022885b8, 0x14000715920}, 0x140008ae080, {{0x0, ...}, ...})
	/Users/mtoohey/Code/ftl/frontend/cli/cmd_new.go:109 +0x3d0
reflect.Value.call({0x1020b7be0?, 0x103343db8?, 0x14000a898f8?}, {0x101594259, 0x4}, {0x14000cbf440, 0x3, 0x100a195d8?})
	/Users/mtoohey/Library/Caches/hermit/pkg/go-1.23.2/src/reflect/value.go:581 +0x97c
reflect.Value.Call({0x1020b7be0?, 0x103343db8?, 0x14000a899f8?}, {0x14000cbf440?, 0x102256a20?, 0x14000a89930?})
	/Users/mtoohey/Library/Caches/hermit/pkg/go-1.23.2/src/reflect/value.go:365 +0x94
github.com/alecthomas/kong.callFunction({0x1020b7be0?, 0x103343db8?, 0x14000a89b58?}, 0x14000715a70)
	/Users/mtoohey/go/pkg/mod/github.com/alecthomas/kong@v1.2.1/callbacks.go:98 +0x390
github.com/alecthomas/kong.(*Context).RunNode(0x140008ae080, 0x14000a2a2d0, {0x14000a89e78, 0x1, 0x140006ee140?})
	/Users/mtoohey/go/pkg/mod/github.com/alecthomas/kong@v1.2.1/context.go:798 +0x604
github.com/alecthomas/kong.(*Context).Run(0x1022885b8?, {0x14000a89e78?, 0x140008ae080?, 0x1032f2db0?})
	/Users/mtoohey/go/pkg/mod/github.com/alecthomas/kong@v1.2.1/context.go:823 +0x138
main.main()
	/Users/mtoohey/Code/ftl/frontend/cli/main.go:139 +0x5d4
```

**Comment by matt2e** [comment]
This is resolved already
