### ISSUE TITLE
Intermittent panic triggered

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#3162]
```
Recovered from intermittent panic in analysers: runtime error: invalid memory address or nil pointer dereference
i: 2
extractor: typeenum
extractors: [[initialize inspect] [metadata] [typeenum] [configsecret data database fsm topic typealias typeenumvariant valueenumvariant verb] [validate enums subscription] [transitive] [finalizer]]
extractorRound: [typeenum]
beforeIndex: [initialize inspect metadata]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100bcd51c]

goroutine 386 [running]:
github.com/TBD54566975/ftl/go-runtime/schema.analyzersWithDependencies.func1()
	/Users/aat/dev/ftl/go-runtime/schema/extract.go:315 +0x254
panic({0x102627040?, 0x103a98b80?})
	/Users/aat/Library/Caches/hermit/pkg/go-1.23.2/src/runtime/panic.go:785 +0x124
github.com/TBD54566975/ftl/go-runtime/schema.analyzersWithDependencies()
	/Users/aat/dev/ftl/go-runtime/schema/extract.go:323 +0x1dc
github.com/TBD54566975/ftl/go-runtime/schema.Extract({0x14000f85560?, 0x101e61e8d?})
	/Users/aat/dev/ftl/go-runtime/schema/extract.go:120 +0xd8
github.com/TBD54566975/ftl/go-runtime/compile.Build({0x1029af010, 0x14000a3d6d0}, {0x14000870690, 0x12}, {0x14000f85560, 0x23}, {{0x14000f85560, 0x23}, {0x14000d253b8, 0x2}, ...}, ...)
	/Users/aat/dev/ftl/go-runtime/compile/build.go:320 +0x97c
github.com/TBD54566975/ftl/internal/buildengine/languageplugin.buildGo({0x1029af010, 0x14000a3d6d0}, {0x14000870690, 0x12}, {{{0x14000f85560, 0x23}, {0x14000d253b8, 0x2}, {0x14000d253bc, 0x4}, ...}, ...}, ...)
	/Users/aat/dev/ftl/internal/buildengine/languageplugin/go_plugin.go:163 +0x118
github.com/TBD54566975/ftl/internal/buildengine/languageplugin.buildAndLoadResult({0x1029af010, 0x14000a3d6d0}, {0x14000870690, 0x12}, {{{0x14000f85560, 0x23}, {0x14000d253b8, 0x2}, {0x14000d253bc, 0x4}, ...}, ...}, ...)
	/Users/aat/dev/ftl/internal/buildengine/languageplugin/plugin.go:333 +0x47c
github.com/TBD54566975/ftl/internal/buildengine/languageplugin.(*internalPlugin).run(0x14000034330, {0x1029af010, 0x14000a3d6d0})
	/Users/aat/dev/ftl/internal/buildengine/languageplugin/plugin.go:277 +0x794
created by github.com/TBD54566975/ftl/internal/buildengine/languageplugin.newInternalPlugin in goroutine 353
	/Users/aat/dev/ftl/internal/buildengine/languageplugin/plugin.go:182 +0x154
```

**Comment by stuartwdouglas** [comment]
I have also seen this:

```
Recovered from intermittent panic in analysers: runtime error: invalid memory address or nil pointer dereference
i: 3
extractor: database
extractors: [[initialize inspect] [metadata] [typeenum] [configsecret data database fsm topic typealias typeenumvariant valueenumvariant verb] [validate enums subscription] [transitive] [finalizer]]
extractorRound: [configsecret data database fsm topic typealias typeenumvariant valueenumvariant verb]
beforeIndex: [initialize inspect metadata typeenum]
```
