### ISSUE TITLE
Kotlin module fails to deploy to staging cluster

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#463]
```
w | Oct 06 11:15:48.703 | echo-470b09aea6 | Plugin failed to start, terminating pid 12349
i | Oct 06 11:15:48.686 | echo-470b09aea6 | at xyz.block.ftl.main.MainKt.main(main.kt)
i | Oct 06 11:15:48.686 | echo-470b09aea6 | at xyz.block.ftl.main.MainKt.main(main.kt:29)
i | Oct 06 11:15:48.685 | echo-470b09aea6 | at xyz.block.ftl.client.GrpcKt.makeGrpcClient(grpc.kt:16)
i | Oct 06 11:15:48.685 | echo-470b09aea6 | at java.base/java.net.InetSocketAddress.<init>(Unknown Source)
i | Oct 06 11:15:48.685 | echo-470b09aea6 | at java.base/java.net.InetSocketAddress.checkPort(Unknown Source)
i | Oct 06 11:15:48.685 | echo-470b09aea6 | Exception in thread "main" java.lang.IllegalArgumentException: port out of range:-1
```

I think this is because the endpoint is `http://ftl-controller` in staging, which indeed does not contain a port.

**Comment by alecthomas** [comment]
Fixed in #464
