### ISSUE TITLE
Kotlin `Any` schema param type throws null reference exception

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/ftl#532]
TIL the hard way that the `Any` type in this interface definition `data class EchoResponse(val obj: Any)` doesn't work (I also tried `Any?`)

This can be recreated by replacing the `Echo.kt` code within the `examples/echo-kotlin` with the following code:

```kotlin
package ftl.echo

import ftl.time.TimeModuleClient
import ftl.time.TimeRequest
import xyz.block.ftl.Context
import xyz.block.ftl.Ingress
import xyz.block.ftl.Method
import xyz.block.ftl.Verb

class InvalidInput(val field: String) : Exception()

data class EchoRequest(val name: String)
data class EchoResponse(val obj: Any)

class Echo {
  @Throws(InvalidInput::class)
  @Verb
  @Ingress(Method.GET, "/echo")
  fun echo(context: Context, req: EchoRequest): EchoResponse {
    val response = context.call(TimeModuleClient::time, TimeRequest())
    return EchoResponse("Hello, ${req.name}! The time is ${response.time}.")
  }
}
```

The `mvn compile` command (which executes the generator) will throw this exception

```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.0:compile (compile) on project echo-kotlin: Compilation failure
[ERROR] [ksp] java.lang.NullPointerException
[ERROR] 	at xyz.block.ftl.ksp.Visitor.toSchemaType(SchemaExtractor.kt:130)
[ERROR] 	at xyz.block.ftl.ksp.Visitor.access$toSchemaType(SchemaExtractor.kt:23)
[ERROR] 	at xyz.block.ftl.ksp.Visitor$toSchemaData$1.invoke(SchemaExtractor.kt:87)
[ERROR] 	at xyz.block.ftl.ksp.Visitor$toSchemaData$1.invoke(SchemaExtractor.kt:84)
[ERROR] 	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
[ERROR] 	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:811)
[ERROR] 	at xyz.block.ftl.ksp.Visitor.toSchemaData(SchemaExtractor.kt:89)
[ERROR] 	at xyz.block.ftl.ksp.Visitor.toSchemaType(SchemaExtractor.kt:128)
[ERROR] 	at xyz.block.ftl.ksp.Visitor.toSchemaType$default(SchemaExtractor.kt:94)
[ERROR] 	at xyz.block.ftl.ksp.Visitor.visitFunctionDeclaration(SchemaExtractor.kt:54)
[ERROR] 	at xyz.block.ftl.ksp.Visitor.visitFunctionDeclaration(SchemaExtractor.kt:23)
(... [kendallw] more things but shortened for brevity)
```

**Comment by KendallWeihe** [comment]
Wait, this might span beyond just `Any` type, I also am seeing it on a response type `data class OfferingWrapper(val offerings: List<Offering>)`
