### ISSUE TITLE
Schema param type Double fails to compile 

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/ftl#547]
[This commit](https://github.com/TBD54566975/ftl/commit/425e5bc6500d4fffd6a9328c9e42bd38b834f93a) gave us a better exception message

----

```kotlin
data class Balance(
    val available: Double, // this is the problem
    val currency: String,
)

data class GetBalanceResponse(val balance: Balance)

@Verb
fun getBalance(context: Context, request: GetBalanceRequest): GetBalanceResponse {
    println("getAccount accountId: ${request.accountId}")
    return GetBalanceResponse(Balance(100.0, "US"))
}
```

When I run a `mvn compile` I'm getting a failure

```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.0:compile (compile) on project ftl-module-accounts: Compilation failure
[ERROR] [ksp] java.lang.IllegalArgumentException: Expected module name to be in the form ftl.<module>, but was kotlin.Double
[ERROR] 	at xyz.block.ftl.ksp.Visitor$Companion.moduleName(SchemaExtractor.kt:148)
[ERROR] 	at xyz.block.ftl.ksp.Visitor$Companion.access$moduleName(SchemaExtractor.kt:137)
[ERROR] 	at xyz.block.ftl.ksp.Visitor.toSchemaType(SchemaExtractor.kt:129)
```

But then if I change the type...

```kotlin
    val available: Double
```

...to....

```kotlin
    val available: String
```

...then compilation passes without issue.

**Comment by KendallWeihe** [comment]
There's a tangential question here of, why do we require that modules be namespaced under the `groupId` `ftl.*`?

**Comment by KendallWeihe** [comment]
This has been fixed. Thanks @worstell!
