### ISSUE TITLE
Creating new modules with `ftl init kotlin` builds and deploys but errors on `call`

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#559]
After deploying 2 new modules `hello` and `world` which were created with `ftl init kotlin <name>` I get an error when I try to call them.

```bash
ftl call hello.echo '{"name": "wes"}'

error: Unary RPC failed: unknown: /xyz.block.ftl.v1.VerbService/Call
ftl: error: unknown
```

The `ftl serve` has the following exception:
```bash
error:runner0: Unary RPC failed: unknown: /xyz.block.ftl.v1.VerbService/Call
2023/11/06 08:34:51 ignoring invalid trailer "Content-Type"
error:controller0: Unary RPC failed: unknown: /xyz.block.ftl.v1.VerbService/Call
info:hello: Nov 06, 2023 8:34:51 AM io.grpc.internal.SerializingExecutor run
info:hello: SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@26c279e5
info:hello: java.lang.IllegalArgumentException: Unknown verb: hello.echo
info:hello: 	at xyz.block.ftl.registry.Registry.invoke(Registry.kt:99)
info:hello: 	at xyz.block.ftl.server.Server.Call(Server.kt:33)
info:hello: 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
info:hello: 	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
info:hello: 	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
info:hello: 	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
info:hello: 	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
info:hello: 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:346)
info:hello: 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:860)
info:hello: 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
info:hello: 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
info:hello: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
info:hello: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
info:hello: 	at java.base/java.lang.Thread.run(Thread.java:833)
info:hello:
error:controller0: Unary RPC failed: unknown: /xyz.block.ftl.v1.VerbService/Call
2023/11/06 08:34:51 ignoring invalid trailer "Content-Type"
```

**Comment by KendallWeihe** [comment]
Additional context here https://github.com/TBD54566975/ftl/issues/548 (title irrelevant to the actual issue)

**Comment by KendallWeihe** [comment]
I actually don't think this is a problem with `ftl init kotlin` per se, but an issue somewhere between the integration point between Kotlin module build & deploy and the ftl cluster hosting those artifacts

For example you can deploy more than one module, and `ftl schema get` will return the proper schemas, but when you go to `ftl call {module}.{verb}` for any module deployed beyond the _first_ module deployed, the call fails.
