### ISSUE TITLE
'No suitable driver found' for MySQL Kotlin integration

### ISSUE THREAD

**Issue by KendallWeihe** [TBD54566975/ftl#564]
Simple Kotlin FTL module intended to ping a locally running MySQL db

```kotlin
package ftl.mysql

import java.sql.Connection
import java.sql.DriverManager
import java.util.Properties
import xyz.block.ftl.Context
import xyz.block.ftl.Verb

data class MysqlRequest(val nothing: String)
data class MysqlResponse(val nothing: String)

class MySql {
  val connection: Connection

  init {
    // todo config these things
    val host = "localhost"
    val port = 3306
    val user = "root"
    val password = "tbd"
    val database = "db-name"
    val info = Properties()
    info["user"] = "root"
    info["password"] = "tbd"

    // Initialize MySQL connection using JDBC
    val url = "jdbc:mysql://${host}:${port}/${database}"
    this.connection = DriverManager.getConnection(url, info)
  }

  @Verb
  fun ping(context: Context, request: MysqlRequest): MysqlResponse {
    println("Connecting to MySQL..")

    val stmt = connection.createStatement()
    val rs = stmt.executeQuery("SELECT 1")

    if (rs.next()) {
      println("Successfully pinged MySQL!")
    } else {
      throw Exception("Failed to ping MySQL.")
    }

    return MysqlResponse("Hello world")
  }
}
```

Throws an error when calling `ftl call mysql.ping`

```
info:mysql: Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/<name>
info:mysql: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
info:mysql: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
info:mysql: 	at ftl.mysql.MySql.<init>(Module.kt:28)
info:mysql: 	... 24 more
error:controller0: Unary RPC failed: unknown: /xyz.block.ftl.v1.VerbService/Call
2023/11/06 18:39:28 ignoring invalid trailer "Content-Type"
```

I've confirmed the local MySQL instance is running (it's running within a Docker container but which is published to be addressable from the local network interface)

```
ftl/examples on  main via 🐹 v1.21.3 via ☕ v17.0.6 on 🐳 v24.0.6
➜ mysql -h 127.0.0.1 -P 3306 -u root -p

Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 8.0.32 MySQL Community Server - GPL

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

@KendallWeihe can provide more context

**Comment by alecthomas** [comment]
I'm not sure how JDBC works exactly, but this indicates to me that there's no MySQL driver registered with JDBC? The docs [indicate](https://dev.mysql.com/doc/connector-j/en/connector-j-usagenotes-connect-drivermanager.html) you might need to instantiate the driver explicitly, have you done that?

**Comment by KendallWeihe** [comment]
Uhh that may be the case... but that would strike me as odd. What's odd is I have this code running in a classic java command-line app which connects to the same db without issue. It's only when I deploy the code to the FTL cluster that this issue arises. I presumed it has something to do with the way the FTL Kotlin runner is setup 🤔 

I can try to interface with an RDS instance and see if I run into the same issues (will have to do tomorrow tho)

**Comment by alecthomas** [comment]
This was due to a missing dependency in the module code.
