### ISSUE TITLE
Maven errors when running `ftl-dev`

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#586]
I pulled down latest this morning and it seems likes `ftl serve` is working ok, but `ftl-dev` fails with the following errors

```
….0-SNAPSHOT.jar| [INFO] -------------------------------------------------------
….0-SNAPSHOT.jar| [INFO]  T E S T S
….0-SNAPSHOT.jar| [INFO] -------------------------------------------------------
….0-SNAPSHOT.jar| [INFO] Running xyz.block.ftl.registry.RegistryTest
….0-SNAPSHOT.jar| [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! -- in xyz.block.ftl.registry.RegistryTest
….0-SNAPSHOT.jar| [ERROR] xyz.block.ftl.registry.RegistryTest -- Time elapsed: 0.004 s <<< ERROR!
….0-SNAPSHOT.jar| java.lang.NoClassDefFoundError: xyz/block/ftl/registry/VerbRef
….0-SNAPSHOT.jar| 	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
….0-SNAPSHOT.jar| 	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
….0-SNAPSHOT.jar| 	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| Caused by: java.lang.ClassNotFoundException: xyz.block.ftl.registry.VerbRef
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
….0-SNAPSHOT.jar| 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
….0-SNAPSHOT.jar| 	... 4 more
….0-SNAPSHOT.jar|
….0-SNAPSHOT.jar| [INFO] Running xyz.block.ftl.registry.VerbHandleTest
….0-SNAPSHOT.jar| [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.011 s <<< FAILURE! -- in xyz.block.ftl.registry.VerbHandleTest
….0-SNAPSHOT.jar| [ERROR] xyz.block.ftl.registry.VerbHandleTest.testInvoke -- Time elapsed: 0.004 s <<< ERROR!
….0-SNAPSHOT.jar| java.lang.NoClassDefFoundError: xyz/block/ftl/serializer/SerializerKt
….0-SNAPSHOT.jar| 	at xyz.block.ftl.registry.VerbHandleTest.<init>(VerbHandleTest.kt:7)
….0-SNAPSHOT.jar| 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
….0-SNAPSHOT.jar| 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
….0-SNAPSHOT.jar| 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| Caused by: java.lang.ClassNotFoundException: xyz.block.ftl.serializer.SerializerKt
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
….0-SNAPSHOT.jar| 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
….0-SNAPSHOT.jar| 	... 6 more
….0-SNAPSHOT.jar|
….0-SNAPSHOT.jar| [INFO] Running xyz.block.ftl.registry.SchemaReflectorKtTest
….0-SNAPSHOT.jar| [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 s <<< FAILURE! -- in xyz.block.ftl.registry.SchemaReflectorKtTest
….0-SNAPSHOT.jar| [ERROR] xyz.block.ftl.registry.SchemaReflectorKtTest.reflectSchemaFromFunc -- Time elapsed: 0.005 s <<< ERROR!
….0-SNAPSHOT.jar| java.lang.NoClassDefFoundError: xyz/block/ftl/v1/schema/Verb
….0-SNAPSHOT.jar| 	at xyz.block.ftl.registry.SchemaReflectorKtTest.reflectSchemaFromFunc(SchemaReflectorKtTest.kt:13)
….0-SNAPSHOT.jar| 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| Caused by: java.lang.ClassNotFoundException: xyz.block.ftl.v1.schema.Verb
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
….0-SNAPSHOT.jar| 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
….0-SNAPSHOT.jar| 	... 4 more
….0-SNAPSHOT.jar|
….0-SNAPSHOT.jar| [INFO] Running xyz.block.ftl.schemaextractor.ExtractSchemaRuleTest
….0-SNAPSHOT.jar| [WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0 s -- in xyz.block.ftl.schemaextractor.ExtractSchemaRuleTest
….0-SNAPSHOT.jar| [INFO] Running xyz.block.ftl.ContextTest
….0-SNAPSHOT.jar| [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.157 s <<< FAILURE! -- in xyz.block.ftl.ContextTest
….0-SNAPSHOT.jar| [ERROR] xyz.block.ftl.ContextTest.endToEnd(TestCase)[1] -- Time elapsed: 0.008 s <<< ERROR!
….0-SNAPSHOT.jar| java.lang.NoClassDefFoundError: xyz/block/ftl/registry/Registry
….0-SNAPSHOT.jar| 	at xyz.block.ftl.ContextTest.endToEnd(ContextTest.kt:55)
….0-SNAPSHOT.jar| 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| Caused by: java.lang.ClassNotFoundException: xyz.block.ftl.registry.Registry
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
….0-SNAPSHOT.jar| 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
….0-SNAPSHOT.jar| 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
….0-SNAPSHOT.jar| 	... 46 more
….0-SNAPSHOT.jar|
….0-SNAPSHOT.jar| [ERROR] xyz.block.ftl.ContextTest.endToEnd(TestCase)[2] -- Time elapsed: 0.001 s <<< ERROR!
….0-SNAPSHOT.jar| java.lang.NoClassDefFoundError: xyz/block/ftl/registry/Registry
….0-SNAPSHOT.jar| 	at xyz.block.ftl.ContextTest.endToEnd(ContextTest.kt:55)
….0-SNAPSHOT.jar| 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
….0-SNAPSHOT.jar| 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
….0-SNAPSHOT.jar| Caused by: java.lang.ClassNotFoundException: xyz.block.ftl.registry.Registry
….0-SNAPSHOT.jar| 	... 46 more
….0-SNAPSHOT.jar|
….0-SNAPSHOT.jar| [INFO]
….0-SNAPSHOT.jar| [INFO] Results:
….0-SNAPSHOT.jar| [INFO]
….0-SNAPSHOT.jar| [ERROR] Errors:
….0-SNAPSHOT.jar| [ERROR]   ContextTest.endToEnd:55 NoClassDefFound xyz/block/ftl/registry/Registry
….0-SNAPSHOT.jar| [ERROR]   ContextTest.endToEnd:55 NoClassDefFound xyz/block/ftl/registry/Registry
….0-SNAPSHOT.jar| [ERROR]   RegistryTest » NoClassDefFound xyz/block/ftl/registry/VerbRef
….0-SNAPSHOT.jar| [ERROR]   SchemaReflectorKtTest.reflectSchemaFromFunc:13 NoClassDefFound xyz/block/ftl/v1/schema/Verb
….0-SNAPSHOT.jar| [ERROR]   VerbHandleTest.<init>:7 NoClassDefFound xyz/block/ftl/serializer/SerializerKt
….0-SNAPSHOT.jar| [INFO]
….0-SNAPSHOT.jar| [ERROR] Tests run: 7, Failures: 0, Errors: 5, Skipped: 2
….0-SNAPSHOT.jar| [INFO]
….0-SNAPSHOT.jar| [INFO] ------------------------------------------------------------------------
….0-SNAPSHOT.jar| [INFO] BUILD FAILURE
….0-SNAPSHOT.jar| [INFO] ------------------------------------------------------------------------
….0-SNAPSHOT.jar| [INFO] Total time:  2.847 s
….0-SNAPSHOT.jar| [INFO] Finished at: 2023-11-10T09:31:53-07:00
….0-SNAPSHOT.jar| [INFO] ------------------------------------------------------------------------
….0-SNAPSHOT.jar| [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.1.2:test (default-test) on project ftl-runtime:
….0-SNAPSHOT.jar| [ERROR]
….0-SNAPSHOT.jar| [ERROR] Please refer to /Users/wesbillman/dev/ftl/kotlin-runtime/ftl-runtime/target/surefire-reports for the individual test results.
….0-SNAPSHOT.jar| [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
….0-SNAPSHOT.jar| [ERROR] -> [Help 1]
….0-SNAPSHOT.jar| [ERROR]
….0-SNAPSHOT.jar| [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
….0-SNAPSHOT.jar| [ERROR] Re-run Maven using the -X switch to enable full debug logging.
….0-SNAPSHOT.jar| [ERROR]
….0-SNAPSHOT.jar| [ERROR] For more information about the errors and possible solutions, please read the following articles:
….0-SNAPSHOT.jar| [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
….0-SNAPSHOT.jar| Bitfile:109:11:   build:
                          ^
    error: build failed: build failed: failed to run command "mvn -N install\nmvn -pl :ftl-runtime install": exit status 1```

**Comment by wesbillman** [comment]
`just install-runtime-jar` also has this error.

**Comment by wesbillman** [comment]
It seems like a `mvn clean install` fixes this for me.
